# _config.yml - Minima Jekyll site config for CCP-SAS

# Site Settings
locale: "en-US"
title: "CCP-SAS"
email: "info@ccpsas.org"
description: "Open-source infrastructure for atomistic modelling of small-angle scattering data"
url: "https://butlerpd.github.io"
#repository: "butlerpd/ccpsas.github.io"
#logo: "/assets/images/ccpsas_logo.png"
theme: minima

header_pages:
  - about.md
  - news.md
  - people.md

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-remote-theme

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ccpsas"
    - label: "Contact"
      icon: "fas fa-envelope"
      url: "mailto:info@ccpsas.org"
