# _config.yml - Minima Jekyll site config for CCP-SAS

# Site Settings
locale: "en-US"
title: "CCP-SAS"
email: "info@ccpsas.org"
description: "Open-source infrastructure for atomistic modelling of small-angle scattering data"
url: "https://butlerpd.github.io"
repository: "butlerpd/ccpsas.github.io"
#logo: "/assets/images/ccpsas_logo.png"
theme: minima
#remote_theme: "mmistakes/minimal-mistakes"

# Minimal Mistakes setting
#minimal_mistakes_skin: default

header_pages:
  - index.md
  - about.md
  - news.md
  - people.md

# Author
author:
  name: "CCP-SAS Team"
  avatar: "/assets/images/avatar.png"
  bio: "Community for Collaborative Computational Projects in Small-Angle Scattering"
  location: "USA / UK / EU"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-remote-theme

# Sidebar Navigation for Docs
collections:
  posts:
    output: true
  docs:
    output: true
    permalink: /:collection/:path/
    sidebar:
      nav: "docs"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: false
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "single"
      sidebar:
        nav: "docs"
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: false
      toc: false
      toc_sticky: true
      classes: wide


# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ccpsas"
    - label: "Contact"
      icon: "fas fa-envelope"
      url: "mailto:info@ccpsas.org"
